Parameters:
  apiGatewayName:
    Type: String
    Default: veiculos-shoppping

Resources:
  apiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Api Gateway
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: !Ref apiGatewayName

Outputs:
  apiGatewayRestApiId:
    Value:
      Ref: apiGateway
    Export:
      Name: apiGateway-restApiId
  apiGatewayRestApiRootResourceId:
    Value:
      Fn::GetAtt:
        - apiGateway
        - RootResourceId
    Export:
      Name: apiGateway-rootResourceId