version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-m06wlr8avqhe"
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "DynamodbStreamsArn=\"arn:aws:dynamodb:us-east-1:647610929809:table/OrdersMarceloortiz/stream/2022-12-17T12:22:01.554\" AuditBucketName=\"orders-audity-bucket-20221217122208996400000001\""
image_repositories = []
