service: vehicles-service

frameworkVersion: '3'

configValidationMode: error
deprecationNotificationMode: error

provider:
  iam:
    role:
      statements:
        - Action:
            - lambda:InvokeAsync
            - lambda:InvokeFunction
          Effect: Allow
          Resource: '*'
  memorySize: 128
  name: aws
  region: us-east-1
  runtime: nodejs16.x
  stage: dev
  versionFunctions: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  get-vehicle:
    handler: src/adapter/in/function/get/index.handle
    events:
      - http:
          path: vehicles
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: false
  
  post-vehicle:
    handler: src/adapter/in/function/save/index.handle
    events:
      - http:
          path: vehicles
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: false

package:
  patterns:
    - '!.vscode/**'
    - '!.editorconfig'
    - '!.terraform'
    - '!.env'
    - '!.env.**'
    - '!.gitignore'
    - '!.git'
    - '!README.md'
    - '!yarn.log'
    - '!yarn.lock'
    - '!package-lock.json'
    - '!.prettierrc'
    - '!.eslintrc.js'