version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-world-marcelo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rqbiz5slu34s"
s3_prefix = "hello-world-marcelo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
