version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "teste-abc123"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-m06wlr8avqhe"
s3_prefix = "teste-abc123"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "StudentName=\"Marceloortiz\""
image_repositories = []
