version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "testing-sagas"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-m06wlr8avqhe"
s3_prefix = "testing-sagas"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "StudentName=\"Marcelo\""
image_repositories = []
